# Generated by Django 3.1.7 on 2023-05-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.ManyToManyField(to='app.ItemColor'),
        ),
    ]
