# Generated by Django 3.1.7 on 2023-05-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20230512_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='full_name',
            field=models.CharField(default='hh', max_length=100),
            preserve_default=False,
        ),
    ]
